# Generated by Django 4.0.2 on 2022-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0002_alter_material_options_remove_good_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='вага в грамах'),
        ),
    ]
