# Generated by Django 4.0.2 on 2022-02-22 15:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0003_alter_good_first_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='rate_field',
            field=models.DecimalField(decimal_places=0, default=Decimal('5'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='відсоток на викуп'),
        ),
    ]
