# Generated by Django 4.0.2 on 2022-02-20 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0003_alter_good_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='redemption_time',
            field=models.DateField(verbose_name='кінцева дата викупу'),
        ),
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='вага в грамах'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='проба'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='ціна за грам (в гривнях)'),
        ),
    ]
