# Generated by Django 4.0.2 on 2022-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0004_alter_good_redemption_time_alter_good_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('AS', 'очікує викупу'), ('BC', 'належить клієнтові'), ('BP', 'належить ломбарду'), ('SL', 'продано ломбардом')], default='AS', max_length=2, verbose_name='статус товару'),
        ),
    ]
